version: "3.8"
services:
  app:
    build: .
    container_name: nest-app
    ports:
      - "8080:8081"
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://user:password@db:5433/mydb"

  db:
    image: postgres:latest
    container_name: nest-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres